"""Depth processing utilities for the Smart Bike vision pipeline.

The :class:`DepthProcessor` consumes rectification data generated by
``stereo_calibrate`` and produces depth-map artefacts from synchronised stereo
frames.  The public API intentionally mirrors the simplified requirements from
this redesign: provide left/right frames and receive a saved ``.npz`` depth
package in return.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional

import cv2
import numpy as np

from .calibrate.calib import load_calibration


@dataclass(slots=True)
class DepthResult:
    depth_map: np.ndarray
    disparity_map: np.ndarray
    num_disparities: int
    file_path: Optional[Path]
    metadata: dict


class DepthProcessor:
    """Compute depth maps from stereo frames."""

    def __init__(
        self,
        calibration_file: str | Path,
        output_dir: str | Path = "./data/depth_maps",
        min_disparity: int = 0,
        num_disparities: int = 16 * 5,
        block_size: int = 5,
    ) -> None:
        self.calibration_file = Path(calibration_file)
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

        (
            self.left_map_x,
            self.left_map_y,
            self.right_map_x,
            self.right_map_y,
            self.image_size,
            self.Q,
        ) = load_calibration(str(self.calibration_file))

        block_size = block_size if block_size % 2 == 1 else block_size + 1
        self.stereo = cv2.StereoSGBM_create(
            minDisparity=min_disparity,
            numDisparities=max(16, num_disparities),
            blockSize=max(3, block_size),
            preFilterCap=31,
            uniquenessRatio=10,
            speckleWindowSize=100,
            speckleRange=32,
            disp12MaxDiff=1,
            mode=cv2.STEREO_SGBM_MODE_SGBM_3WAY,
        )

    # ------------------------------------------------------------------
    # Core API
    # ------------------------------------------------------------------
    def process(
        self,
        left_frame: np.ndarray,
        right_frame: np.ndarray,
        save: bool = True,
        filename: str | None = None,
    ) -> DepthResult:
        """Compute the depth map for ``left_frame``/``right_frame``."""
        rect_left, rect_right = self._rectify(left_frame, right_frame)
        disp = self._compute_disparity(rect_left, rect_right)
        depth = self._disparity_to_depth(disp)

        file_path: Optional[Path] = None
        if save:
            file_path = self._save(depth, disp, filename)

        metadata = {
            "timestamp": datetime.now().isoformat(),
            "calibration_file": str(self.calibration_file),
        }
        return DepthResult(depth, disp, self.stereo.getNumDisparities(), file_path, metadata)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------
    def _rectify(
        self, left_frame: np.ndarray, right_frame: np.ndarray
    ) -> tuple[np.ndarray, np.ndarray]:
        rect_left = cv2.remap(left_frame, self.left_map_x, self.left_map_y, cv2.INTER_LINEAR)
        rect_right = cv2.remap(right_frame, self.right_map_x, self.right_map_y, cv2.INTER_LINEAR)
        return rect_left, rect_right

    def _compute_disparity(
        self, left_rect: np.ndarray, right_rect: np.ndarray
    ) -> np.ndarray:
        gray_left = cv2.cvtColor(left_rect, cv2.COLOR_BGR2GRAY)
        gray_right = cv2.cvtColor(right_rect, cv2.COLOR_BGR2GRAY)
        disparity = self.stereo.compute(gray_left, gray_right).astype(np.float32) / 16.0
        disparity[disparity < 0] = 0
        return disparity

    def _disparity_to_depth(self, disparity: np.ndarray) -> np.ndarray:
        points = cv2.reprojectImageTo3D(disparity, self.Q)
        depth = points[:, :, 2]
        depth[~np.isfinite(depth)] = 0
        depth = np.maximum(depth, 0)
        return depth

    def _save(
        self, depth: np.ndarray, disparity: np.ndarray, filename: str | None
    ) -> Path:
        timestamp = filename or datetime.now().strftime("%Y%m%d_%H%M%S_%f")[:-3]
        file_path = self.output_dir / f"depth_{timestamp}.npz"
        np.savez_compressed(
            file_path,
            depth=depth.astype(np.float32),
            disparity=disparity.astype(np.float32),
            num_disparities=int(self.stereo.getNumDisparities()),
            calibration_file=str(self.calibration_file),
        )
        return file_path


__all__ = ["DepthProcessor", "DepthResult"]
