#!/usr/bin/env bash
# Set up a Radxa Rock Pi (RK3588) environment for running YOLO11 RKNN demos.
#
# This script installs the required system packages, prepares a Python virtual
# environment, installs Python dependencies (Ultralytics + RKNN toolkit), and
# generates a RKNN-tailored copy of `yolo/live_demo.py` that defaults to the
# `yolo11n.rknn` weights file.
#
# Usage:
#   chmod +x scripts/setup_rockpi.sh
#   ./scripts/setup_rockpi.sh
#
# After the script completes, activate the environment and run the RKNN demo:
#   source venv-rockpi/bin/activate
#   python yolo/live_demo_rockpi.py --source 0

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
VENV_DIR="${REPO_ROOT}/venv-rockpi"
LIVE_DEMO_SRC="${REPO_ROOT}/yolo/live_demo.py"
LIVE_DEMO_DST="${REPO_ROOT}/yolo/live_demo_rockpi.py"
RKNN_WEIGHTS="${REPO_ROOT}/yolo/yolo11n.rknn"

echo "[INFO] Repository root: ${REPO_ROOT}"

if [[ ! -f "${RKNN_WEIGHTS}" ]]; then
  echo "[ERROR] RKNN weights not found at ${RKNN_WEIGHTS}"
  echo "        Copy yolo11n.rknn into the yolo/ directory before running this script."
  exit 1
fi

if [[ ! -f "${LIVE_DEMO_SRC}" ]]; then
  echo "[ERROR] Source demo script not found at ${LIVE_DEMO_SRC}"
  exit 1
fi

if ! command -v sudo >/dev/null 2>&1; then
  echo "[ERROR] sudo is required to install system packages."
  exit 1
fi

echo "[STEP] Updating apt package index…"
sudo apt-get update

echo "[STEP] Installing system packages…"
sudo apt-get install -y \
  python3 python3-venv python3-pip python3-opencv \
  git curl wget unzip pkg-config \
  v4l-utils \
  rockchip-rknpu2 || {
    echo "[WARN] Failed to install rockchip-rknpu2 via apt. Ensure librknnrt is installed manually if required."
  }

if [[ -d "${VENV_DIR}" ]]; then
  echo "[STEP] Virtual environment already exists at ${VENV_DIR}"
else
  echo "[STEP] Creating virtual environment at ${VENV_DIR}…"
  python3 -m venv "${VENV_DIR}"
fi

echo "[STEP] Upgrading pip and installing Python dependencies…"
"${VENV_DIR}/bin/pip" install --upgrade pip
"${VENV_DIR}/bin/pip" install \
  ultralytics==8.3.152 \
  rknn-toolkit-lite2==1.7.1 \
  numpy \
  opencv-python \
  onnxruntime \
  tqdm

echo "[STEP] Generating RKNN-specific live demo script…"
python3 - <<'PY'
from pathlib import Path

repo_root = Path(__file__).resolve().parents[1]
src = repo_root / "yolo" / "live_demo.py"
dst = repo_root / "yolo" / "live_demo_rockpi.py"

text = src.read_text()

replacements = {
    'DEFAULT_WEIGHTS = ROOT / "yolo11n.pt"': 'DEFAULT_WEIGHTS = ROOT / "yolo11n.rknn"',
    'YOLO11n Live Demo': 'YOLO11n RKNN Live Demo',
}

for needle, replacement in replacements.items():
    if needle not in text:
        raise RuntimeError(f"Expected token not found: {needle}")
    text = text.replace(needle, replacement, 1)

header = (
    "# NOTE: This file is auto-generated by scripts/setup_rockpi.sh.\n"
    "# It mirrors yolo/live_demo.py but defaults to the RKNN weights on Rock Pi hardware.\n"
    "# Do not edit directly; modify the source template instead.\n\n"
)

dst.write_text(header + text)
print(f"[INFO] Created {dst.relative_to(repo_root)}")
PY

echo ""
echo "[DONE] Setup complete."
echo "       Activate the environment with: source ${VENV_DIR}/bin/activate"
echo "       Run the demo with: python yolo/live_demo_rockpi.py --source 0"

